# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 오늘의풍경 | Scenery of Today
email: info@sceneryoftoday.kr
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sceneryoftoday.kr" # the base hostname & protocol for your site
twitter_username: sceneryoftoday
github_username:  helloinah
permalink: date

# Build settings
markdown: kramdown